/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bolao_copa;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import jxl.write.WriteException;

/**
 *
 * @author Emerson Jr.
 */
public class Atualiza_S_I extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Importação
     *
     * @param metAllR
     * @param jAllR
     * @param main
     */
    public Atualiza_S_I(Metodos_AllRoles metAllR, JogosAllRoles jAllR, MainWindow main) {
        initComponents();
        this.metAllR = metAllR;
        this.main = main;
        this.jAllR = jAllR;
        enfeite1.setVisible(false);
        enfeite2.setVisible(false);
        enfeite3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        enfeite3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        enfeite1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        enfeite2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        barraProgresso = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        lInforme = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Constantes.getVersion());
        setPreferredSize(new java.awt.Dimension(528, 225));
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Atualizacao de Dados!");
        jPanel1.add(jLabel2);
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        enfeite3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enfeite3.setText("Enf.");
        jPanel2.add(enfeite3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        enfeite1.setText("Enf.");
        jPanel3.add(enfeite1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        enfeite2.setText("Enf.");
        jPanel4.add(enfeite2);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.GridLayout(5, 1));
        jPanel5.add(jLabel4);

        barraProgresso.setBackground(new java.awt.Color(255, 255, 255));
        barraProgresso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        barraProgresso.setForeground(new java.awt.Color(0, 0, 0));
        barraProgresso.setMaximum(64);
        barraProgresso.setStringPainted(true);
        jPanel5.add(barraProgresso);
        jPanel5.add(jLabel5);

        lInforme.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lInforme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lInforme.setText("Atualizando dados, por favor aguarde!");
        jPanel5.add(lInforme);
        jPanel5.add(jLabel6);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private final Metodos_AllRoles metAllR;
    private final MainWindow main;
    private final JogosAllRoles jAllR;
    private String campanha;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    private javax.swing.JLabel enfeite1;
    private javax.swing.JLabel enfeite2;
    private javax.swing.JLabel enfeite3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lInforme;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
//        synchronized (this) {
        this.setVisible(true);
//            JOptionPane.showMessageDialog(this, "Aguarde enquanto atualizamos as informações, isto pode demorar!");
        if ("Edição de Informações".equals(jAllR.getLabelTittle().getText())
                || "Realize suas Apostas".equals(jAllR.getLabelTittle().getText())) {
            if (Constantes.getWgroup() == 2) {
                try {
                    JOptionPane.showMessageDialog(this, metAllR.doApostas(this));
                } catch (SQLException ex) {
                    Logger.getLogger(JogosAllRoles.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, metAllR.doUpdate(this));
            }
        } else {
            //System.out.println(campanha);
            JOptionPane.showMessageDialog(this, metAllR.doResultado(campanha, this));
        }
        jAllR.Limpa();
        this.setVisible(false);        
//            notify();
//        }
        main.setVisible(true);
    }
    
    public void setCampanha(String campanha) {
        this.campanha = campanha;
    }
    
    public javax.swing.JProgressBar getBarraProgresso() {
        return barraProgresso;
    }
}
