/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bolao_copa;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Emerson Jr.
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     *
     * @param main
     * @param met
     * @param metCadUs
     */
    public CadastroUsuario(MainWindow main, Metodos_Comum met, Metodos_Cadastro_Usuario metCadUs) {
        initComponents();
        this.main = main;
        this.met = met;
        this.metCadUs = metCadUs;
        enfeite1.setVisible(false);
        enfeite2.setVisible(false);
        getRootPane().setDefaultButton(saveButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        labelUser = new javax.swing.JLabel();
        comboUser = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        comboGrupoPrivil = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        checkAtivo = new javax.swing.JCheckBox();
        checkSenha = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        enfeite2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        enfeite1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Constantes.getVersion());
        setPreferredSize(new java.awt.Dimension(826, 461));
        setResizable(false);

        jPanel3.setLayout(new java.awt.GridLayout(5, 1));

        jPanel12.setLayout(new java.awt.GridLayout(2, 1));

        labelUser.setText("Usuário:");
        jPanel12.add(labelUser);

        comboUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUserActionPerformed(evt);
            }
        });
        jPanel12.add(comboUser);

        jPanel3.add(jPanel12);

        jPanel11.setLayout(new java.awt.GridLayout(2, 1));

        jLabel17.setText("Escolha o Grupo pertencente:");
        jPanel11.add(jLabel17);

        jPanel11.add(comboGrupoPrivil);

        jPanel3.add(jPanel11);

        jPanel10.setLayout(new java.awt.GridLayout(2, 1));

        jLabel18.setText("Nome:");
        jPanel10.add(jLabel18);
        jPanel10.add(nameField);

        jPanel3.add(jPanel10);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        checkAtivo.setText("Ativo");
        jPanel8.add(checkAtivo);

        checkSenha.setText("Quebrar senha");
        checkSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSenhaActionPerformed(evt);
            }
        });
        jPanel8.add(checkSenha);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(2, 2, 15, 0));

        jLabel19.setText("Login");
        jPanel9.add(jLabel19);

        jLabel20.setText("Senha");
        jPanel9.add(jLabel20);
        jPanel9.add(loginField);
        jPanel9.add(passwordField);

        jPanel3.add(jPanel9);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));
        jPanel6.add(jLabel1);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cadastro de Usuário:");
        jPanel6.add(jLabel15);
        jPanel6.add(jLabel16);

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(3, 5));
        jPanel4.add(jLabel2);
        jPanel4.add(jLabel3);
        jPanel4.add(jLabel4);
        jPanel4.add(jLabel5);
        jPanel4.add(jLabel6);
        jPanel4.add(jLabel11);

        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel4.add(saveButton);
        jPanel4.add(jLabel7);

        cancelButton.setText("Voltar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel4.add(cancelButton);
        jPanel4.add(jLabel8);
        jPanel4.add(jLabel9);
        jPanel4.add(jLabel10);
        jPanel4.add(jLabel12);
        jPanel4.add(jLabel13);
        jPanel4.add(jLabel14);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.GridLayout(1, 1));

        enfeite2.setText("ENFE");
        jPanel5.add(enfeite2);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel7.setLayout(new java.awt.GridLayout(1, 1));

        enfeite1.setText("ENFE");
        jPanel7.add(enfeite1);

        getContentPane().add(jPanel7, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        aux_txt = "";
        if ("editar".equals(saveButton.getText().toLowerCase()) && comboUser.getSelectedIndex() == 0) {
            aux_txt = "Escolha um Usuário!\n";
        }
        if (comboGrupoPrivil.getSelectedIndex() == 0) {
            aux_txt = aux_txt + "Escolha um grupo!\n";
        }
        if ("".equals(nameField.getText())) {
            aux_txt = aux_txt + "Preencha o campo nome!\n";
        }
        if ("".equals(loginField.getText())) {
            aux_txt = aux_txt + "Preencha o campo login!\n";
        }
        if (checkSenha.isSelected()) {
            if ("".equals(met.passToString(passwordField.getPassword()))) {
                aux_txt = aux_txt + "Preencha o campo senha!\n";
            }
        }
        try {
            if (!"".equals(aux_txt)) {
                JOptionPane.showMessageDialog(this, "Por favor verifique as inconsistencias:\n" + aux_txt);
            } else {
                aux_txt = metCadUs.doCadastro(Integer.parseInt(comboGrupoPrivil.getSelectedItem().toString().split(" - ")[0]),
                        nameField.getText().toUpperCase(), loginField.getText().toUpperCase(), met.passToString(passwordField.getPassword()),
                        checkAtivo.isSelected(), checkSenha.isSelected(), "salvar".equals(saveButton.getText().toLowerCase()));
                if ("0".equals(aux_txt)) {
                    aux_txt = "Usuário "
                            + loginField.getText().toUpperCase()
                            + " existente!";
                } else if ("salvar".equals(saveButton.getText().toLowerCase())) {
                    aux_txt = "Usuário "
                            + loginField.getText().toUpperCase()
                            + " criado com o código: " + aux_txt;
                } else {
                    aux_txt = "Usuário "
                            + loginField.getText().toUpperCase()
                            + ", referente ao codigo " + aux_txt + " editado!";
                }
                JOptionPane.showMessageDialog(this, aux_txt);
                Limpa();
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Deseja Realmente sair?", Constantes.getVersion(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            Limpa();
            this.setVisible(false);
            main.setVisible(true);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void checkSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSenhaActionPerformed
        if (checkSenha.isSelected()) {
            passwordField.setEnabled(true);
        } else {
            passwordField.setEnabled(false);
            passwordField.setText("");
        }
    }//GEN-LAST:event_checkSenhaActionPerformed

    private void comboUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUserActionPerformed
        if (comboUser.getSelectedIndex() != 0) {
            metCadUs.doForm(comboUser.getSelectedItem().toString(), comboGrupoPrivil, nameField, checkAtivo, loginField);
        }
    }//GEN-LAST:event_comboUserActionPerformed
    private String aux_txt;
    private boolean first = false;
    private final Metodos_Comum met;
    private final MainWindow main;
    private final Metodos_Cadastro_Usuario metCadUs;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox checkAtivo;
    private javax.swing.JCheckBox checkSenha;
    private javax.swing.JComboBox<String> comboGrupoPrivil;
    private javax.swing.JComboBox<String> comboUser;
    private javax.swing.JLabel enfeite1;
    private javax.swing.JLabel enfeite2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTextField loginField;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    public void setTipo(boolean editar) {
        try {
            checkAtivo.setVisible(editar);
            checkSenha.setVisible(editar);
            checkSenha.setSelected(!editar);
            passwordField.setEnabled(!editar);
            comboUser.setVisible(editar);
            labelUser.setVisible(editar);
            loginField.setEnabled(!editar);
            if (editar) {
                saveButton.setText("Editar");
                met.makeJCBUser(comboUser);
            } else {
                saveButton.setText("Salvar");
                checkAtivo.setSelected(!editar);
            }
            if (!first) {
                met.makeJCBUser(comboUser);
                met.makeJCBGrupo(comboGrupoPrivil);
                first = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Limpa() {
        comboGrupoPrivil.setSelectedIndex(0);
        comboUser.setSelectedIndex(0);
        nameField.setText("");
        passwordField.setText("");
        checkAtivo.setSelected(false);
        if ("salvar".equals(saveButton.getText().toLowerCase())) {
            checkSenha.setSelected(false);
        } else {
            checkSenha.setSelected(true);
        }
        checkSenha.doClick();
        loginField.setText("");
        aux_txt = "";
    }
}
